#!/bin/bash


if git status | grep 'nothing to commit' &> /dev/null; then
    echo 'Nothing to autosave just yet. Make a change you would like to save!'
    exit 1
fi
set -x
exec curl http://localhost:5001/ --data "message=$*"
