
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-data
  namespace: anubis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-provisioner

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  namespace: anubis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-data
  namespace: anubis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: nfs-provisioner
