---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: anubis
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - name: web
    port: 80
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: anubis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: anubis
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: anubis
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: web
    port: 9200
    targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: anubis
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - name: web
    port: 5601
    targetPort: 5601
