### ELK stack
# - Elasticsearch
# - Logstash
# - Kibana

## Logstash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: anubis

spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: registry.osiris.services/anubis/logstash:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 9200
        env:
        - name: "discovery.type"
          value: "single-node"
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-data
        persistentVolumeClaim:
          claimName: elastic-data

---

## Elasticsearch
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: anubis

spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 9200
        env:
        - name: "discovery.type"
          value: "single-node"
        volumeMounts:
        - name: elastic-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-data
        persistentVolumeClaim:
          claimName: elastic-data
---
## kibana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: anubis

spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.5.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: anubis
  labels:
    app: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:
  - name: logstash
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: anubis
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - name: web
    port: 9200
    targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: anubis
  labels:
    app: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - name: web
    port: 5601
    targetPort: 5601

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data
  namespace: anubis
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
