#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel 2> /dev/null)"
if [ ! "${REPO_ROOT}" ]; then
    echo 'You are not in a git repo! Please navigate to one to save something!'
    exit 1
fi

if git status | grep 'nothing to commit' &> /dev/null; then
    echo 'Nothing to autosave just yet. Make a change you would like to save!'
    exit 2
fi

exec curl http://localhost:5001/ --data "repo=${REPO_ROOT}&message=$*"