#!/bin/bash

if [ "$(cat /AUTOSAVE)" = "OFF" ]; then
    echo 'Autosave was disabled for this session.'
    exit 1
fi

if git status | grep 'nothing to commit' &> /dev/null; then
    echo 'Nothing to autosave just yet. Make a change you would like to save!'
    exit 1
fi

exec curl http://localhost:5001/ \
     --data "message=${@}"
