apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: anubis-api

spec:
  selector:
    matchLabels:
      app: anubis-api
  replicas: {{ .Values.api.replicas }}
  {{- if .Values.api.rollingUpdates }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 10
  {{- end }}
  template:
    metadata:
      labels:
        app: anubis-api
    spec:
      # dnsPolicy: Default
      nodeSelector:
        datacenter: mtc
      containers:
      - name: anubis-api
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: web
          containerPort: 5000
        resources:
         {{- toYaml .Values.api.resources | nindent 10 }}
        env:
        - name: "DEBUG"
          value: {{- if .Values.debug }} "1"{{- else }} "0"{{- end }}
        - name: "DISABLE_ELK"
          value: "0"
        # Gunicorn workers
        - name: "WORKERS"
          value: {{ .Values.api.workers | quote }}
        - name: "GUNICORN_OPTIONS"
          value: "--capture-output --enable-stdio-inheritance --preload --timeout 30"
        - name: "SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: api
              key: secret-key
        - name: "OAUTH_CONSUMER_KEY"
          valueFrom:
            secretKeyRef:
              name: oauth
              key: consumer-key
        - name: "OAUTH_CONSUMER_SECRET"
          valueFrom:
            secretKeyRef:
              name: oauth
              key: consumer-secret
        - name: DB_HOST
          value: mariadb.mariadb.svc.cluster.local
        # sqlalchemy uri
        - name: "DATABASE_URI"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-uri
        {{- if .Values.api.healthCheck }}
        livenessProbe:
          exec:
            command:
              - curl
              - http://localhost:5000/
          initialDelaySeconds: 120
          periodSeconds: 5
        {{- end }}

      # Mail container
      - name: smtp
        image: namshi/smtp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis-debug
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-debug
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

spec:
  selector:
    matchLabels:
      app: anubis-debug
  template:
    metadata:
      labels:
        app: anubis-debug
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: jupyter
        image: registry.osiris.services/anubis/api-dev:v2.0.0
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 5003
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        env:
          - name: DB_HOST
            value: mariadb.mariadb.svc.cluster.local
          # sqlalchemy uri
          - name: "DATABASE_URI"
            valueFrom:
              secretKeyRef:
                name: api
                key: database-uri

      - name: adminer
        image: adminer
        env:
        - name: "ADMINER_DEFAULT_SERVER"
          value: "mariadb.mariadb.svc.cluster.local"
        ports:
        - name: adminer
          containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: anubis-api
  ports:
  - name: web
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: anubis-debug
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-debug
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: anubis-debug
  ports:
  - name: adminer
    port: 5002
    targetPort: 8080
  - name: jupyter
    port: 5003
    targetPort: 5003

---
# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  stripPrefix:
    prefixes:
      - "/api"
---
# Declaring the user list
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: private-api-basicauth
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

spec:
  basicAuth:
    secret: private-api-basicauth

---
# Note: in a kubernetes secret the string (e.g. generated by htpasswd) must be base64-encoded first.
# To create an encoded user:password pair, the following command can be used:
# htpasswd -nb user password | openssl base64

apiVersion: v1
kind: Secret
metadata:
  name: private-api-basicauth
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

data:
  users: |2
    bGludXhpc2xvdmU6JDJ5JDA1JEptLldYL1Nrb2h1WHNkZWZuaE1OdWVod1kwc2tN
    RTRubG5JSEs0NnpLS0hxNlM3b1RPVjJD

---
# Public Ingress Route /api/public/*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.api.public
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/api/`)
    middlewares:
    {{- if .Values.vpnOnly }}
    - name: whitelist-vpn
      namespace: traefik
    {{- end }}
    - name: strip-api
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis
      port: 5000
  tls:
    certResolver: tls

---
# Private Ingress Route /api/private/*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.api.private
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis-api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/api/private/`)
    middlewares:
    {{- if .Values.vpnOnly }}
    - name: whitelist-vpn
      namespace: traefik
    {{- end }}
    - name: strip-api
      namespace: {{ .Release.Namespace }}
    - name: private-api-basicauth
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis
      port: 5000
  tls:
    certResolver: tls
