
## Redis cache
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: redis

spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379


