FROM registry.osiris.services/anubis/assignment-base:ubuntu-20.04

# Switch to the root user to install stuff
# USER root
# RUN apt update \
#   && apt install -y qemu-system-x86

COPY assignment.py .
COPY assignment.yml .
