{{- if .Values.theia.enable }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-proxy
  namespace: anubis
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: theia-proxy

spec:
  replicas: {{ .Values.theia.proxy.replicas }}
  {{- if .Values.rollingUpdates }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
      revisionHistoryLimit: 10
  {{- end }}
  selector:
    matchLabels:
      app: theia
      component: proxy
  template:
    metadata:
      labels:
        app: theia
        role: proxy
        component: proxy
    spec:
      containers:
      - name: proxy
        image: {{ .Values.theia.proxy.image }}:{{ .Values.theia.proxy.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: "SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: api
              key: secret-key
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-password
        - name: "DB_HOST"
          value: "mariadb.mariadb.svc.cluster.local"

---

apiVersion: v1
kind: Service
metadata:
  name: theia-proxy
  namespace: anubis

spec:
  selector:
    app: theia
    component: proxy
  ports:
    - name: http-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-udp
      protocol: UDP
      port: 5000
      targetPort: 5000


---

# Public Ingress Route /api/public/*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.theia.public
  namespace: anubis
  labels:
    app: theia

spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.theia.proxy.domain }}`)
    services:
    - name: theia-proxy
      port: 5000
  tls:
    certResolver: tls


---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: theia-session-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  podSelector:
    matchLabels:
      app: theia
      role: theia-session
      network-policy: student
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: theia
          role: proxy

    ports:
    - protocol: TCP
      port: 5000
    - protocol: UDP
      port: 5000
  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32

     # Github IP Addresses
    - ipBlock:
        cidr: 192.30.252.0/22
    - ipBlock:
        cidr: 185.199.108.0/22
    - ipBlock:
        cidr: 140.82.112.0/20
    - ipBlock:
        cidr: 13.114.40.48/32
    - ipBlock:
        cidr: 52.192.72.89/32
    - ipBlock:
        cidr: 52.69.186.44/32
    - ipBlock:
        cidr: 15.164.81.167/32
    - ipBlock:
        cidr: 52.78.231.108/32
    - ipBlock:
        cidr: 13.234.176.102/32
    - ipBlock:
        cidr: 13.234.210.38/32
    - ipBlock:
        cidr: 13.229.188.59/32
    - ipBlock:
        cidr: 13.250.177.223/32
    - ipBlock:
        cidr: 52.74.223.119/32
    - ipBlock:
        cidr: 13.236.229.21/32
    - ipBlock:
        cidr: 13.237.44.5/32
    - ipBlock:
        cidr: 52.64.108.95/32
    - ipBlock:
        cidr: 18.228.52.138/32
    - ipBlock:
        cidr: 18.228.67.229/32
    - ipBlock:
        cidr: 18.231.5.6/32
    - ipBlock:
        cidr: 18.181.13.223/32
    - ipBlock:
        cidr: 54.238.117.237/32
    - ipBlock:
        cidr: 54.168.17.15/32
    - ipBlock:
        cidr: 3.34.26.58/32
    - ipBlock:
        cidr: 13.125.114.27/32
    - ipBlock:
        cidr: 3.7.2.84/32
    - ipBlock:
        cidr: 3.6.106.81/32
    - ipBlock:
        cidr: 18.140.96.234/32
    - ipBlock:
        cidr: 18.141.90.153/32
    - ipBlock:
        cidr: 18.138.202.180/32
    - ipBlock:
        cidr: 52.63.152.235/32
    - ipBlock:
        cidr: 3.105.147.174/32
    - ipBlock:
        cidr: 3.106.158.203/32
    - ipBlock:
        cidr: 54.233.131.104/32
    - ipBlock:
        cidr: 18.231.104.233/32
    - ipBlock:
        cidr: 18.228.167.86/32

    ports:

    # HTTP
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

    # DNS
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53


{{- end }}
