FROM os3224-assignment-base

COPY test.py test.py
COPY test-0.py test-0.py
COPY test-1.py test-1.py
COPY test-2.py test-2.py
COPY test-3.py test-3.py
COPY test-4.py test-4.py
COPY test-5.py test-5.py
COPY test-6.py test-6.py
