
{{- if .Values.reaper.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-ide-reaper
  labels:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    component: reaper
spec:
  schedule: {{ .Values.reaper.schedule | quote }}
  suspend: {{ .Values.reaper.suspend }}
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        component: ide-reaper-job
    spec:
      template:
        spec:
          {{- if and .Values.nodeSelector (not .Values.debug) }}
          nodeSelector:
            {{ .Values.nodeSelector }}
          {{- end }}
          serviceAccountName: {{ include "chart.fullname" . }}-rpc
          restartPolicy: Never
          containers:
          - name: reaper
            image: "{{ .Values.api.image }}:{{ .Values.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
            command: ["python3", "anubis/jobs/ide_reaper.py"]
            env:
            - name: "JOB"
              value: "1"
            {{- include "api.env" . | nindent 12 }}
{{- end }}
