---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    job: db-migrate-{{ .Release.Revision }}
    component: db-migrate
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrate
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["alembic", "upgrade", "head"]
        env:
        - name: "REDIS_PASS"
          valueFrom:
            secretKeyRef:
              name: api
              key: redis-password
        - name: "DATABASE_URI"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-uri
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-password
        - name: "DB_HOST"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-host
        - name: "DB_PORT"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-port
