{{- if .Values.reporter.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: anubis-reporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anubis-reporter
    component: "anubis-reporter"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  schedule: {{ .Values.reporter.schedule | quote }}
  suspend: {{ .Values.reporter.suspend }}
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: anubis
        component: reporter-job
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: reporter
            image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
            command: ["python3", "jobs/reporter.py"]
            env:
            - name: "PYTHONPATH"
              value: "/opt/app"
            - name: "DEBUG"
              value: {{- if .Values.debug }} "1"{{- else }} "0"{{- end }}
            - name: "JOB"
              value: "1"
            - name: "DISABLE_ELK"
              value: "0"
            - name: "LOGGER_NAME"
              value: "reporter"
            - name: "REDIS_PASS"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: redis-password
            - name: "DATABASE_URI"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-uri
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-password
            - name: "DB_HOST"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-host
            - name: "DATABASE_PORT"
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-port
            - name: "DISCORD_WEBHOOK_URL"
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: webhook-url
{{- end }}
