#
# Use this to propagate new ide images to the kubernetes cluster
#   kubectl apply -f theia-prop.yaml
#

{{- if .Values.theia.prop.enable }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "chart.fullname" . }}-theia-prop
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: theia-prop
    tag: {{ .Values.tag | quote }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      name: theia-prop
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        name: theia-prop
        tag: {{ .Values.tag | quote }}
    spec:
      containers:
      {{- range .Values.theia.prop.images }}
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: Always
        command: ['sh', '-c']
        args: ['while true; do sleep 3600; done']
      {{- end }}
{{- end }}