
{{- if .Values.reaper.enable }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-visuals
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    component: "visuals"
spec:
  schedule: {{ .Values.visuals.schedule | quote }}
  suspend: {{ .Values.visuals.suspend }}
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        component: visuals
    spec:
      template:
        spec:
          {{- if and .Values.nodeSelector (not .Values.debug) }}
          nodeSelector:
            {{ .Values.nodeSelector | toYaml }}
          {{- end }}
          restartPolicy: Never
          containers:
          - name: visuals
            image: "{{ .Values.api.image }}:{{ .Values.tag }}"
            imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
            command: ["python3", "anubis/jobs/visuals.py"]
            env:
            - name: "JOB"
              value: "1"
            {{- include "api.env" . | nindent 12 }}
{{- end }}
