"""ADD assignment repo timestamps

Revision ID: 145674891fee
Revises: 2d4e34d460e8
Create Date: 2021-08-18 17:31:05.045961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "145674891fee"
down_revision = "2d4e34d460e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_repo",
        sa.Column("created", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "assignment_repo",
        sa.Column("last_updated", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment_repo", "last_updated")
    op.drop_column("assignment_repo", "created")
    # ### end Alembic commands ###
