"""ADD timestamps to assignment questions

Revision ID: 24999cac49d5
Revises: 265635dac5b6
Create Date: 2021-03-21 12:35:43.926002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "24999cac49d5"
down_revision = "265635dac5b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_question",
        sa.Column("created", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "assignment_question",
        sa.Column("last_updated", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment_question", "last_updated")
    op.drop_column("assignment_question", "created")
    # ### end Alembic commands ###
