"""add_committer_info

Revision ID: 2c08c087b8e9
Revises: d5de41411043
Create Date: 2022-09-11 23:56:01.380925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2c08c087b8e9"
down_revision = "d5de41411043"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "committer_name",
            mysql.TEXT(collation="utf8mb4_general_ci", length=16384),
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "committer_email",
            mysql.TEXT(collation="utf8mb4_general_ci", length=16384),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "committer_email")
    op.drop_column("user", "committer_name")
    # ### end Alembic commands ###
