"""ADD autograde_tests_repo

Revision ID: 31dc6a1a6759
Revises: 716e3e14891d
Create Date: 2021-05-20 20:57:40.110207

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31dc6a1a6759"
down_revision = "716e3e14891d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course",
        sa.Column(
            "autograde_tests_repo",
            sa.TEXT(),
            nullable=False,
            default="https://github.com/os3224/anubis-assignment-tests",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "autograde_tests_repo")
    # ### end Alembic commands ###
