"""ADD custom join code

Revision ID: 3890c28bd2cb
Revises: 2af8f3918f87
Create Date: 2021-06-13 09:28:47.780360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3890c28bd2cb"
down_revision = "2af8f3918f87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("name_2", table_name="assignment")
    op.drop_index("pipeline_image_2", table_name="assignment")
    op.create_index(
        op.f("ix_assignment_name"), "assignment", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_assignment_pipeline_image"),
        "assignment",
        ["pipeline_image"],
        unique=False,
    )
    op.add_column(
        "course", sa.Column("join_code", sa.String(length=256), nullable=True)
    )
    op.create_unique_constraint(None, "course", ["join_code"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "course", type_="unique")
    op.drop_column("course", "join_code")
    op.drop_index(
        op.f("ix_assignment_pipeline_image"), table_name="assignment"
    )
    op.drop_index(op.f("ix_assignment_name"), table_name="assignment")
    op.create_index(
        "pipeline_image_2", "assignment", ["pipeline_image"], unique=False
    )
    op.create_index("name_2", "assignment", ["name"], unique=False)
    # ### end Alembic commands ###
