"""ADD pipeline_log

Revision ID: 47ffcba2ffc1
Revises: 5396e908cf7b
Create Date: 2022-09-22 20:03:07.508654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "47ffcba2ffc1"
down_revision = "5396e908cf7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission",
        sa.Column(
            "pipeline_log",
            mysql.TEXT(collation="utf8mb4_general_ci", length=65536),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "pipeline_log")
    # ### end Alembic commands ###
