"""CHG unique repo_url

Revision ID: 4bc9f91bd338
Revises: 592c0d556edf
Create Date: 2021-08-24 13:44:22.602730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4bc9f91bd338"
down_revision = "592c0d556edf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "assignment_repo", ["repo_url"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assignment_repo", type_="unique")
    # ### end Alembic commands ###
