"""ADD diff column for SubmissionTestResult

Revision ID: 4c841c36d745
Revises: a143a9fa5199
Create Date: 2021-12-18 18:33:05.029882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4c841c36d745"
down_revision = "a143a9fa5199"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission_test_result", sa.Column("diff", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission_test_result", "diff")
    # ### end Alembic commands ###
