"""ADD source to user

Revision ID: 5786747278fd
Revises: d8e685b73889
Create Date: 2023-10-01 13:51:34.641044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5786747278fd"
down_revision = "d8e685b73889"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source",
                sa.Enum("NYU", "GITHUB", name="usersource"),
                nullable=False,
            )
        )
    conn = op.get_bind()
    with conn.begin():
        conn.execute("UPDATE `user` SET `source` = 'NYU';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("source")
    # ### end Alembic commands ###
