"""INIT

Revision ID: 6182584a4bb4
Revises: 
Create Date: 2021-01-08 00:10:16.159340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6182584a4bb4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assigned_student_question",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=True),
        sa.Column("assignment_id", sa.String(length=128), nullable=False),
        sa.Column("question_id", sa.String(length=128), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["assignment_question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assigned_student_question_assignment_id"),
        "assigned_student_question",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assigned_student_question_question_id"),
        "assigned_student_question",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "submission",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=True),
        sa.Column("assignment_id", sa.String(length=128), nullable=False),
        sa.Column("assignment_repo_id", sa.String(length=128), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("commit", sa.String(length=128), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("token", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assignment_repo_id"],
            ["assignment_repo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_assignment_id"),
        "submission",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submission_commit"), "submission", ["commit"], unique=True
    )
    op.create_index(
        op.f("ix_submission_owner_id"),
        "submission",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "theia_session",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("owner_id", sa.String(length=128), nullable=False),
        sa.Column("assignment_id", sa.String(length=128), nullable=False),
        sa.Column("repo_id", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("cluster_address", sa.String(length=256), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("ended", sa.DateTime(), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=True),
        sa.Column("last_proxy", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["assignment_repo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submission_build",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("submission_id", sa.String(length=128), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_build_submission_id"),
        "submission_build",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "submission_test_result",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("submission_id", sa.String(length=128), nullable=False),
        sa.Column("assignment_test_id", sa.String(length=128), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_test_id"],
            ["assignment_test.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.PrimaryKeyConstraint("id", "submission_id", "assignment_test_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("submission_test_result")
    op.drop_index(
        op.f("ix_submission_build_submission_id"),
        table_name="submission_build",
    )
    op.drop_table("submission_build")
    op.drop_table("theia_session")
    op.drop_index(op.f("ix_submission_owner_id"), table_name="submission")
    op.drop_index(op.f("ix_submission_commit"), table_name="submission")
    op.drop_index(op.f("ix_submission_assignment_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(
        op.f("ix_assigned_student_question_question_id"),
        table_name="assigned_student_question",
    )
    op.drop_index(
        op.f("ix_assigned_student_question_assignment_id"),
        table_name="assigned_student_question",
    )
    op.drop_table("assigned_student_question")
    # ### end Alembic commands ###
