"""RM theia-persistent column from assignment

Revision ID: b17b8f54b3af
Revises: 587921276e67
Create Date: 2021-08-17 15:55:47.478660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b17b8f54b3af"
down_revision = "587921276e67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment", "theia_persistent_storage")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment",
        sa.Column(
            "theia_persistent_storage",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
