"""ADD test points

Revision ID: df5aa182233f
Revises: 074fa1ed980b
Create Date: 2022-01-15 21:28:49.796788

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df5aa182233f"
down_revision = "074fa1ed980b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_test", sa.Column("points", sa.Integer(), nullable=True)
    )
    conn = op.get_bind()
    conn.execute('update assignment_test set points = 10;')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment_test", "points")
    # ### end Alembic commands ###
