name: Anubis Main CD/CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  # Test Stage.
  test-api:
    defaults:
      run:
        shell: bash
        working-directory: api
    runs-on: ubuntu-latest
    concurrency: test
    environment: anubis
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: actions/cache@v2
      id: cache-venv  # name for referring later
      with:
        path: |
          **/venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements/dev.txt') }}-${{ hashFiles('../.github/workflows/test-api.yml') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Install dependencies
      run: |
        set -ex
        python -m venv venv
        if [ -f requirements/dev.txt ]; then ./venv/bin/pip install -r requirements/dev.txt; fi
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Background API
      run: |
        set -ex
        env MINDEBUG=1 MIGRATE=1 ./venv/bin/python3 dev.py &
    - name: Test with pytest
      run: |
        ./tests/mintest.sh
    - name: Teardown
      run: |
        killall -9 python3
  test-web:
    name: test web
    runs-on: ubuntu-latest
    concurrency: test
    environment: anubis
    defaults:
      run:
        shell: bash
        working-directory: web
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run build

  # Build Stage.
  # Will build the docker image, and push it
  # to the container registry.
  build-api:
    name: build api
    needs: [test-api, test-web]
    runs-on: ubuntu-latest
    concurrency: build
    environment: anubis
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into DigitalOcean container registry
        run: doctl registry login
      - name: Build container image
        run: docker compose build api
      - name: Push image to registry
        run: docker compose push api
  build-web:
    name: build web
    needs: [test-api, test-web]
    runs-on: ubuntu-latest
    concurrency: build
    environment: anubis
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into DigitalOcean container registry
        run: doctl registry login
      - name: Build container image
        run: docker compose build web
      - name: Push image to registry
        run: docker compose push web
  build-theia-proxy:
    name: build theia proxy
    needs: [test-api, test-web]
    runs-on: ubuntu-latest
    concurrency: build
    environment: anubis
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log into DigitalOcean container registry
        run: doctl registry login
      - name: Build container image
        run: docker compose build theia-proxy
      - name: Push image to registry
        run: docker compose push theia-proxy

  # Deploy step.
  # Will push out yaml to the k8s cluster, then restart
  # deployments.
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment: anubis
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save anubis
      - name: Helm upgrade
        run: make upgrade
      - name: Rollout restarts to deployments
        run: make restart
      - name: Verify deployment
        run: make status