name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '37 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue is stale'
        stale-pr-message: 'PR is stale'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
