FROM python:3.8

WORKDIR /opt/app

RUN pip3 install flask flask-mysql pymysql gunicorn \
  python-geoip-geolite2 \
  python-geoip-python3 \
  elasticsearch

COPY . .

CMD gunicorn -b 0.0.0.0:5000 -w 10 bomblab-resultd:app
