env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  parser: '@babel/eslint-parser'
  requireConfigFile: false
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - jsx
rules:
  react/prop-types: off
  require-jsdoc: 0
  valid-jsdoc: 0
  camelcase: 0
  no-unused-vars: 0
  react/display-name: off
  indent: ["warn", 2]
  max-len: ["warn", { "code": 120 }]
  quote-props: ["off", "consistent-as-needed"]
